.github/workflows/test.yml, README.md
=> Add project description

.github/workflows/test.yml, srv/AuthoritySrv.srv
=> Add `remove` field

srv/AuthoritySrv.srv
=> Change field name

.github/workflows/test.yml
**Checks**
This PR closes #13.
=> Fix test command

.github/workflows/test.yml
**Checks**
This PR closes #19.
=> Make test suite more descriptive

CMakeLists.txt, msg/CoordArrayMsg.msg
**Checks**
This PR closes #24.
=> Implement coordinate array interface

CMakeLists.txt, msg/TimedAzElInt64.msg
**Checks**
This PR closes #26.
=> Add message type definition

.github/workflows/gh-pages.yml, .gitignore, docs/generate_docs.py
**Checks**
This PR closes #28.
=> Auto-generate documentation

docs/generate_docs.py
=> Change title font in documentation

.github/workflows/gh-pages.yml, docs/generate_docs.py, msg/AlertMsg.msg, msg/CoordMsg.msg, msg/PIDMsg.msg, msg/TimedAzElFloat64.msg, msg/TimedAzElInt64.msg, srv/AuthoritySrv.srv
**Checks**
This PR closes #31.
=> Support Sphinx-like section in docs

CMakeLists.txt, srv/File.srv
**Checks**
This PR closes #33.
=> Add data type for file transfer service

msg/AlertMsg.msg, srv/File.srv
**Checks**
This PR closes #35.
=> Change data type for threshold field of `AlertMsg`

CMakeLists.txt, msg/TimedFloat64.msg
**Checks**
This PR closes #37.
=> #37 add TimeFloat64.msg

CMakeLists.txt, srv/RecordSrv.srv
**Checks**
This PR closes #39.
=> Add record status management interface

msg/AlertMsg.msg
**Checks**
This PR closes #41.
=> Change field name of `AlertMsg`

CMakeLists.txt, msg/ChopperMsg.msg
**Checks**
This PR closes #43.
=> Add chopper command message

CMakeLists.txt, msg/CoordCmdMsg.msg
**Checks**
This PR closes #45.
=> Refactor message definition for coordinate command

CMakeLists.txt, docs/generate_docs.py, msg/Spectral.msg
**Checks**
This PR closes #48.
=> Add spectral data type

CMakeLists.txt, msg/BiasMsg.msg
**Checks**
This PR closes #50.
=> #50 Add bias information message

CMakeLists.txt, msg/ControlStatus.msg
**Checks**
This PR closes #54.
=> #54 Add control status message

msg/ControlStatus.msg
**Checks**
This PR closes #56.
=> #56 Add timestamp field

CMakeLists.txt, msg/QLookMeta.msg
**Checks**
This PR closes #58.
=> Add definition of Q-Look configuration message

CMakeLists.txt, msg/QLookMeta.msg, msg/Spectral.msg
**Checks**
This PR closes #58.
=> #58 Move metadata definitions to Spectral message

msg/Spectral.msg
**Checks**
This PR closes #61.
=> Add integration time field

CMakeLists.txt, msg/BiasMsg.msg, msg/LocalSignal.msg
**Checks**
This PR closes #63.
=> Add device command and telemetry interfaces

msg/LocalSignal.msg
**Checks**
This PR closes #63.
=> Add timestamp field

msg/BiasMsg.msg
**Checks**
This PR closes #66.
=> Add power field to `BiasMsg`

CMakeLists.txt, msg/Clock.msg
**Checks**
This PR closes #68.
=> Add observatory clock data interface

CMakeLists.txt, msg/DeviceReading.msg
**Checks**
This PR closes #70.
=> Add DeviceReading message definition

msg/CoordCmdMsg.msg
**Checks**
This PR closes #72.
=> Add offset coordinate parameters

msg/ControlStatus.msg
**Checks**
This PR closes #74.
=> Add tight control flag

CMakeLists.txt, msg/Boolean.msg
**Checks**
This PR closes #76.
=> Add boolean message

CMakeLists.txt, msg/TrackingStatus.msg
**Checks**
This PR closes #78.
=> Add tracking status message

CMakeLists.txt, msg/Sampling.msg
**Checks**
This PR closes #80.
=> Add cardinality reduction parameter message

CMakeLists.txt, msg/ObservingMode.msg, srv/ObservationMode.srv
**Checks**
This PR closes #86.
=> Add observation mode interfaces

CMakeLists.txt, msg/Binning.msg
**Checks**
This PR closes #90 .
=> #90 add binning msg

msg/WeatherMsg.msg, srv/CoordinateCommand.srv
=> #93 antenna alt az mode

CMakeLists.txt, msg/CCDMsg.msg
**Checks**
This PR closes #92.
=> Add `CCDMsg` for the optical pointing

CMakeLists.txt, msg/CCDMsg.msg, srv/CCDCommand.srv
=> #96 ccd srv

CMakeLists.txt, msg/LocalAttenuator.msg, msg/LocalAttenuatorMsg.msg
=> #99 new msg LocalAttenuator

msg/LocalAttenuatorMsg.msg
=> #101 change LocalAttenuatorMsg

CMakeLists.txt, msg/TimeOnly.msg, srv/ComDelaySrv.srv
=> add test communication delay

CMakeLists.txt, msg/MirrorMsg.msg
**Checks**
This PR closes #104
=> [WIP] #104 add MirrorMsg

msg/MirrorMsg.msg
=> change mirror msg

CMakeLists.txt, msg/MembraneMsg.msg
**Checks**
This PR closes #108
=> #108 add membrane msg

CMakeLists.txt, srv/DomeLimit.srv
=> #111 domelimit

CMakeLists.txt, msg/CalcLog.msg, srv/CoordinateCommand.srv
=> #98 scan param

CMakeLists.txt, msg/DriveMsg.msg
**Checks**
This PR closes #118
=> #118 drive

CMakeLists.txt, msg/DomeOC.msg, srv/DomeOC.srv
=> #114 add DomeOC.msg

msg/DomeOC.msg
**Checks**
This PR closes #120
=> #120 add move to DomeOC

CMakeLists.txt, msg/DomeLimit.msg, srv/DomeLimit.srv
**Checks**
This PR closes #123
=> #123 topic

msg/HEMTBias.msg, msg/LocalSignal.msg, msg/SISBias.msg
**Checks**
This PR closes #125
=> #125 nasco

msg/LocalAttenuatorMsg.msg, msg/SISBias.msg
**Checks**
This PR closes #127
=> #127 add fin for att

msg/RecordMsg.msg
=> debug record msg

CMakeLists.txt, msg/TPModeMsg.msg
**Checks**
This PR closes #137
=> #137 add TPModeMsg

msg/TPModeMsg.msg
**Checks**
This PR closes #137
=> add tp_range

msg/Spectral.msg
**Checks**
This PR closes #133
=> Record ori time
